# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArdifisicaGui(object):
    def setupUi(self, ArdifisicaGui):
        ArdifisicaGui.setObjectName("ArdifisicaGui")
        ArdifisicaGui.resize(1113, 854)
        self.centralwidget = QtWidgets.QWidget(ArdifisicaGui)
        self.centralwidget.setObjectName("centralwidget")
        self.Led = QtWidgets.QLabel(self.centralwidget)
        self.Led.setGeometry(QtCore.QRect(1060, 220, 41, 21))
        self.Led.setMaximumSize(QtCore.QSize(51, 16777215))
        self.Led.setObjectName("Led")
        self.comboBox_ports = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ports.setGeometry(QtCore.QRect(950, 220, 92, 25))
        self.comboBox_ports.setObjectName("comboBox_ports")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(870, 220, 68, 19))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 220, 141, 601))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.distanciaButton = QtWidgets.QPushButton(self.layoutWidget)
        self.distanciaButton.setObjectName("distanciaButton")
        self.verticalLayout_4.addWidget(self.distanciaButton)
        self.aireButton = QtWidgets.QPushButton(self.layoutWidget)
        self.aireButton.setObjectName("aireButton")
        self.verticalLayout_4.addWidget(self.aireButton)
        self.tacometroButton = QtWidgets.QPushButton(self.layoutWidget)
        self.tacometroButton.setObjectName("tacometroButton")
        self.verticalLayout_4.addWidget(self.tacometroButton)
        self.genSonbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.genSonbutton.setObjectName("genSonbutton")
        self.verticalLayout_4.addWidget(self.genSonbutton)
        self.microfonoButton = QtWidgets.QPushButton(self.layoutWidget)
        self.microfonoButton.setObjectName("microfonoButton")
        self.verticalLayout_4.addWidget(self.microfonoButton)
        self.tempIRbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.tempIRbutton.setObjectName("tempIRbutton")
        self.verticalLayout_4.addWidget(self.tempIRbutton)
        self.luzButton = QtWidgets.QPushButton(self.layoutWidget)
        self.luzButton.setObjectName("luzButton")
        self.verticalLayout_4.addWidget(self.luzButton)
        self.atomizadorButton = QtWidgets.QPushButton(self.layoutWidget)
        self.atomizadorButton.setObjectName("atomizadorButton")
        self.verticalLayout_4.addWidget(self.atomizadorButton)
        self.fotoRButton = QtWidgets.QPushButton(self.layoutWidget)
        self.fotoRButton.setObjectName("fotoRButton")
        self.verticalLayout_4.addWidget(self.fotoRButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(911, 248, 191, 551))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textSerialMedida = QtWidgets.QTextEdit(self.layoutWidget2)
        self.textSerialMedida.setMinimumSize(QtCore.QSize(189, 369))
        self.textSerialMedida.setObjectName("textSerialMedida")
        self.verticalLayout.addWidget(self.textSerialMedida)
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(160, 220, 751, 521))
        self.tabWidget.setMinimumSize(QtCore.QSize(739, 399))
        self.tabWidget.setObjectName("tabWidget")
        self.SimpleView = QtWidgets.QWidget()
        self.SimpleView.setObjectName("SimpleView")
        self.labelSensor = QtWidgets.QLabel(self.SimpleView)
        self.labelSensor.setGeometry(QtCore.QRect(80, 150, 561, 121))
        self.labelSensor.setObjectName("labelSensor")
        self.labelMedida = QtWidgets.QLabel(self.SimpleView)
        self.labelMedida.setGeometry(QtCore.QRect(0, 30, 741, 361))
        self.labelMedida.setObjectName("labelMedida")
        self.widget = QtWidgets.QWidget(self.SimpleView)
        self.widget.setGeometry(QtCore.QRect(3, 381, 704, 101))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.runStopButton = QtWidgets.QPushButton(self.widget)
        self.runStopButton.setMaximumSize(QtCore.QSize(231, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.runStopButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.runStopButton.setFont(font)
        self.runStopButton.setObjectName("runStopButton")
        self.horizontalLayout_2.addWidget(self.runStopButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.groupEncoder = QtWidgets.QGroupBox(self.widget)
        self.groupEncoder.setMinimumSize(QtCore.QSize(481, 99))
        self.groupEncoder.setTitle("")
        self.groupEncoder.setObjectName("groupEncoder")
        self.labelEncoder = QtWidgets.QLabel(self.groupEncoder)
        self.labelEncoder.setGeometry(QtCore.QRect(260, 0, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelEncoder.setFont(font)
        self.labelEncoder.setObjectName("labelEncoder")
        self.widget1 = QtWidgets.QWidget(self.groupEncoder)
        self.widget1.setGeometry(QtCore.QRect(10, 0, 231, 102))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.selectButton = QtWidgets.QPushButton(self.widget1)
        self.selectButton.setMinimumSize(QtCore.QSize(131, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.selectButton.setFont(font)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_7.addWidget(self.selectButton)
        self.dialEncoder = QtWidgets.QDial(self.widget1)
        self.dialEncoder.setObjectName("dialEncoder")
        self.horizontalLayout_7.addWidget(self.dialEncoder)
        self.horizontalLayout_4.addWidget(self.groupEncoder)
        self.labelMedida.raise_()
        self.labelSensor.raise_()
        self.layoutWidget.raise_()
        self.tabWidget.addTab(self.SimpleView, "")
        self.PlotView = QtWidgets.QWidget()
        self.PlotView.setObjectName("PlotView")
        self.grafica = MplWidget(self.PlotView)
        self.grafica.setGeometry(QtCore.QRect(10, 10, 721, 401))
        self.grafica.setObjectName("grafica")
        self.layoutWidget3 = QtWidgets.QWidget(self.PlotView)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 420, 721, 52))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.runStopButton_2 = QtWidgets.QPushButton(self.layoutWidget3)
        self.runStopButton_2.setMaximumSize(QtCore.QSize(231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.runStopButton_2.setFont(font)
        self.runStopButton_2.setObjectName("runStopButton_2")
        self.horizontalLayout_6.addWidget(self.runStopButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.tabWidget.addTab(self.PlotView, "")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(12, 0, 1081, 203))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Logo = QtWidgets.QLabel(self.layoutWidget4)
        self.Logo.setMaximumSize(QtCore.QSize(162, 201))
        self.Logo.setObjectName("Logo")
        self.horizontalLayout_3.addWidget(self.Logo)
        spacerItem4 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.Titulo = QtWidgets.QLabel(self.layoutWidget4)
        self.Titulo.setObjectName("Titulo")
        self.horizontalLayout_3.addWidget(self.Titulo)
        spacerItem5 = QtWidgets.QSpacerItem(278, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 830, 1081, 22))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.correo = QtWidgets.QLabel(self.layoutWidget5)
        self.correo.setObjectName("correo")
        self.horizontalLayout.addWidget(self.correo)
        spacerItem6 = QtWidgets.QSpacerItem(538, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(160, 760, 741, 41))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.termoKButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.termoKButton.setObjectName("termoKButton")
        self.horizontalLayout_5.addWidget(self.termoKButton)
        self.hallButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.hallButton.setObjectName("hallButton")
        self.horizontalLayout_5.addWidget(self.hallButton)
        self.servoButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.servoButton.setObjectName("servoButton")
        self.horizontalLayout_5.addWidget(self.servoButton)
        self.ledRGBbutton = QtWidgets.QPushButton(self.layoutWidget6)
        self.ledRGBbutton.setObjectName("ledRGBbutton")
        self.horizontalLayout_5.addWidget(self.ledRGBbutton)
        self.colorButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.colorButton.setObjectName("colorButton")
        self.horizontalLayout_5.addWidget(self.colorButton)
        ArdifisicaGui.setCentralWidget(self.centralwidget)
        self.menuCOM = QtWidgets.QAction(ArdifisicaGui)
        self.menuCOM.setObjectName("menuCOM")
        self.actionhelp = QtWidgets.QAction(ArdifisicaGui)
        self.actionhelp.setObjectName("actionhelp")
        self.action1200 = QtWidgets.QAction(ArdifisicaGui)
        self.action1200.setObjectName("action1200")
        self.action115200 = QtWidgets.QAction(ArdifisicaGui)
        self.action115200.setObjectName("action115200")
        self.action57600 = QtWidgets.QAction(ArdifisicaGui)
        self.action57600.setObjectName("action57600")
        self.action38400 = QtWidgets.QAction(ArdifisicaGui)
        self.action38400.setObjectName("action38400")
        self.action19200 = QtWidgets.QAction(ArdifisicaGui)
        self.action19200.setObjectName("action19200")
        self.action9600 = QtWidgets.QAction(ArdifisicaGui)
        self.action9600.setObjectName("action9600")
        self.action4800 = QtWidgets.QAction(ArdifisicaGui)
        self.action4800.setObjectName("action4800")
        self.action2400 = QtWidgets.QAction(ArdifisicaGui)
        self.action2400.setObjectName("action2400")
        self.action1200_2 = QtWidgets.QAction(ArdifisicaGui)
        self.action1200_2.setObjectName("action1200_2")

        self.retranslateUi(ArdifisicaGui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ArdifisicaGui)

    def retranslateUi(self, ArdifisicaGui):
        _translate = QtCore.QCoreApplication.translate
        ArdifisicaGui.setWindowTitle(_translate("ArdifisicaGui", "Interfaz gráfica de Ardufísica"))
        self.Led.setText(_translate("ArdifisicaGui", "<html><head/><body><p>led</p><p><br/></p></body></html>"))
        self.label.setText(_translate("ArdifisicaGui", "<html><head/><body><p align=\"right\">COM:</p></body></html>"))
        self.distanciaButton.setText(_translate("ArdifisicaGui", "Distancia"))
        self.aireButton.setText(_translate("ArdifisicaGui", "Calidad Aire"))
        self.tacometroButton.setText(_translate("ArdifisicaGui", "Tacometro"))
        self.genSonbutton.setText(_translate("ArdifisicaGui", "Gen.Sonido"))
        self.microfonoButton.setText(_translate("ArdifisicaGui", "Microfono"))
        self.tempIRbutton.setText(_translate("ArdifisicaGui", "Temperatura IR"))
        self.luzButton.setText(_translate("ArdifisicaGui", "Intensidad. Luz "))
        self.atomizadorButton.setText(_translate("ArdifisicaGui", "Atomizador"))
        self.fotoRButton.setText(_translate("ArdifisicaGui", "Fotorresisten"))
        self.saveButton.setText(_translate("ArdifisicaGui", "Save"))
        self.labelSensor.setText(_translate("ArdifisicaGui", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">TextLabel</span></p><p><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">Prueba</span></p></body></html>"))
        self.labelMedida.setText(_translate("ArdifisicaGui", "<html><head/><body><p><img src=\":/prefijoNuevo/.images/lcd.png\"/></p></body></html>"))
        self.runStopButton.setText(_translate("ArdifisicaGui", "RUN"))
        self.labelEncoder.setText(_translate("ArdifisicaGui", "<html><head/><body><p><br/></p></body></html>"))
        self.selectButton.setText(_translate("ArdifisicaGui", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SimpleView), _translate("ArdifisicaGui", "LCD view"))
        self.runStopButton_2.setText(_translate("ArdifisicaGui", "RUN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PlotView), _translate("ArdifisicaGui", "Plot view"))
        self.Logo.setText(_translate("ArdifisicaGui", "<html><head/><body><p><img src=\":/prefijoNuevo/.images/udea.png\"/></p></body></html>"))
        self.Titulo.setText(_translate("ArdifisicaGui", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#005500;\">ArduFísica GUI V1.0</span></p></body></html>"))
        self.correo.setText(_translate("ArdifisicaGui", "<html><head/><body><p align=\"center\"><span style=\" color:#787878;\">daniel.estrada1@udea.edu.co</span></p></body></html>"))
        self.termoKButton.setText(_translate("ArdifisicaGui", "Termocupla k"))
        self.hallButton.setText(_translate("ArdifisicaGui", "Sensor Hall"))
        self.servoButton.setText(_translate("ArdifisicaGui", "Micro Servo"))
        self.ledRGBbutton.setText(_translate("ArdifisicaGui", "LED R_G_B"))
        self.colorButton.setText(_translate("ArdifisicaGui", "Sensor Color"))
        self.menuCOM.setText(_translate("ArdifisicaGui", "COM"))
        self.actionhelp.setText(_translate("ArdifisicaGui", "help"))
        self.action1200.setText(_translate("ArdifisicaGui", "1200"))
        self.action115200.setText(_translate("ArdifisicaGui", "115200"))
        self.action57600.setText(_translate("ArdifisicaGui", "57600"))
        self.action38400.setText(_translate("ArdifisicaGui", "38400"))
        self.action19200.setText(_translate("ArdifisicaGui", "19200"))
        self.action9600.setText(_translate("ArdifisicaGui", "9600"))
        self.action4800.setText(_translate("ArdifisicaGui", "4800"))
        self.action2400.setText(_translate("ArdifisicaGui", "2400"))
        self.action1200_2.setText(_translate("ArdifisicaGui", "1200"))

from mplwidget import MplWidget
import resource_rc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ArdifisicaGui = QtWidgets.QMainWindow()
    ui = Ui_ArdifisicaGui()
    ui.setupUi(ArdifisicaGui)
    ArdifisicaGui.show()
    sys.exit(app.exec_())

